add vmm_active_uplinks_check + tests + doc
datacenter/ACI-Pre-Upgrade-Validation-Script pull request #112
Opened 2024-04-30 23:01 UTC by monrog2

2024-04-30 23:43 UTC, monrog2 commented
test output:
```
[Check  1/1] fvUplinkOrderCont with blank active uplinks definition...                                            FAIL - OUTAGE WARNING!!
  Tenant  Application Profile  Application EPG  VMM Domain
  ------  -------------------  ---------------  ----------
  test1   ap1                  epg1             test-dvs
  test1   ap2                  epg2             test-dvs
  test1   ap3                  epg3             test-dvs

  Recommended Action: Identify Active Uplinks and apply this to the VMM domain association of each EPG
  Reference Document: https://datacenter.github.io/ACI-Pre-Upgrade-Validation-Script/validations#access-untagged-port-config


[Check  1/1] fvUplinkOrderCont with blank active uplinks definition...                                                               PASS
```
reached out to submitter for doc content review.

2024-05-01 20:11 UTC, monrog2 commented on aci-preupgrade-validation-script.py
> +    doc_url = 'https://datacenter.github.io/ACI-Pre-Upgrade-Validation-Script/validations#access-untagged-port-config'
Need to update this URL with the right section

2024-05-06 20:15 UTC, monrog2 commented
integration tests look good.

pytest output:
```
[Check  1/1] fvUplinkOrderCont with blank active uplinks definition...                                            FAIL - OUTAGE WARNING!!
  Tenant  Application Profile  Application EPG  VMM Domain
  ------  -------------------  ---------------  ----------
  test1   ap1                  epg1             test-dvs
  test1   ap2                  epg2             test-dvs
  test1   ap3                  epg3             test-dvs

  Recommended Action: Identify Active Uplinks and apply this to the VMM domain association of each EPG
  Reference Document: https://datacenter.github.io/ACI-Pre-Upgrade-Validation-Script/validations#vmm-uplink-container-with-empty-actives


[Check  1/1] fvUplinkOrderCont with blank active uplinks definition...                                                               PASS
[Check  1/1] fvUplinkOrderCont with blank active uplinks definition... cversion does not have class fvUplinkOrderCont                 N/A

2024-05-06 21:18 UTC, takishida requested changes

2024-05-06 21:18 UTC, takishida commented on aci-preupgrade-validation-script.py
> +        print_result(title, result, msg, headers, data, recommended_action=recommended_action, doc_url=doc_url)
```suggestion
        print_result(title, result, msg)
```

2024-05-06 21:18 UTC, takishida commented on aci-preupgrade-validation-script.py
> +
```suggestion
```

2024-05-06 21:20 UTC, takishida approved these changes

2024-05-06 21:21 UTC, merged