Issue83
datacenter/ACI-Pre-Upgrade-Validation-Script pull request #113
Opened 2024-05-01 19:48 UTC by jeestr4d

- **Added logic for CSCvn20175 and CSCvt07565**
- **Added logic for CSCvn20175 and CSCvt07565**
- **Added logic for CSCvn20175 and CSCvt07565**

2024-05-01 19:50 UTC, jeestr4d commented
Fix for Issue #83

2024-05-02 20:02 UTC, monrog2 requested changes
1. paste in the output of your local pytest run for this function
2. The associated validation doc likely need an update to mention the new bug.

2024-05-02 20:02 UTC, monrog2 commented on aci-preupgrade-validation-script.py
> +    if cversion.older_than('3.2(5d)') or (cversion.major1 == '4' and cversion.major2 <= '1' and cversion.older_than('4.1(1i)')):  # If current Version is older than 3.2(5d) or for 4.1 version is olde
if you have to keep the comment, put it on a newline

2024-05-02 20:02 UTC, monrog2 commented on aci-preupgrade-validation-script.py
> +    elif (cversion.major1 == '4' and cversion.major2 == '2' and cversion.older_than('4.2(4i)')) or (cversion.major1 == '5' and cversion.older_than('5.0(1k)')):  # If current 4.2 Version is older than
same here, comment on newline

2024-05-03 04:22 UTC, jeestr4d commented on aci-preupgrade-validation-script.py
> +    elif (cversion.major1 == '4' and cversion.major2 == '2' and cversion.older_than('4.2(4i)')) or (cversion.major1 == '5' and cversion.older_than('5.0(1k)')):  # If current 4.2 Version is older than
1. Local pytest function run
`tests/eventmgr_db_defect_check/test_eventmgr_db_defect_check.py::test_logic[3.2(5e)-PASS] PASSED                                         [ 20%]
tests/eventmgr_db_defect_check/test_eventmgr_db_defect_check.py::test_logic[3.2(10g)-PASS] PASSED                                        [ 21%]
tests/eventmgr_db_defect_check/test_eventmgr_db_defect_check.py::test_logic[4.1(2a)-PASS] PASSED                                         [ 21%]
tests/eventmgr_db_defect_check/test_eventmgr_db_defect_check.py::test_logic[4.2(4j)-PASS] PASSED                                         [ 22%]
tests/eventmgr_db_defect_check/test_eventmgr_db_defect_check.py::test_logic[5.0(1l)-PASS] PASSED                                         [ 22%]
tests/eventmgr_db_defect_check/test_eventmgr_db_defect_check.py::test_logic[3.2(4a)-FAIL - UPGRADE FAILURE!!] PASSED                     [ 23%]
tests/eventmgr_db_defect_check/test_eventmgr_db_defect_check.py::test_logic[4.0(1a)-FAIL - UPGRADE FAILURE!!] PASSED                     [ 23%]
tests/eventmgr_db_defect_check/test_eventmgr_db_defect_check.py::test_logic[4.2(3a)-FAIL - UPGRADE FAILURE!!] PASSED                     [ 23%]
tests/eventmgr_db_defect_check/test_eventmgr_db_defect_check.py::test_logic[5.0(1a)-FAIL - UPGRADE FAILURE!!] PASSED                     [ 24%]
tests`
2. Branch updated to include doc_url
3. Removed comments

2024-05-08 19:08 UTC, monrog2 commented
closing this one, will work on branch sourced from here.

2024-05-08 19:08 UTC, closed without merging