11 add cvt07565 check
datacenter/ACI-Pre-Upgrade-Validation-Script pull request #118
Opened 2024-05-09 14:08 UTC by monrog2

for #11 , spun off of jeestrads forked branch

2024-05-09 23:10 UTC, monrog2 commented
TODO:
- finish updating logic to check BD to EPG  reln
- Add  documentation

2024-05-13 21:17 UTC, monrog2 commented
Can collapse into 2 vs 3 requests if required. 

as is, pytests pass and integration checks are good:
```
[Check  1/1] BD and EPG Subnet Scope Check... 0 EPG Subnets found. Skipping.                                                          N/A
[Check  1/1] BD and EPG Subnet Scope Check...                                                                     FAIL - OUTAGE WARNING!!
  BD DN                   BD Scope  EPG DN                               EPG Scope
  -----                   --------  ------                               ---------
  uni/tn-common/BD-myBd2  public    uni/tn-test/ap-testApp/epg-testepg   shared
  uni/tn-test3/BD-myBd3   public    uni/tn-test3/ap-testApp/epg-testepg  shared

  Recommended Action: Configure the same Scope for the identified subnet pairings
  Reference Document: https://bst.cloudapps.cisco.com/bugsearch/bug/CSCvv30303


[Check  1/1] BD and EPG Subnet Scope Check...                                                                     FAIL - OUTAGE WARNING!!
  BD DN                   BD Scope  EPG DN                               EPG Scope
  -----                   --------  ------                               ---------
  uni/tn-common/BD-myBd2  public    uni/tn-test/ap-testApp/epg-testepg   shared
  uni/tn-test3/BD-myBd3   public    uni/tn-test3/ap-testApp/epg-testepg  shared

  Recommended Action: Configure the same Scope for the identified subnet pairings
  Reference Document: https://bst.cloudapps.cisco.com/bugsearch/bug/CSCvv30303


[Check  1/1] BD and EPG Subnet Scope Check...                                                                                        PASS
```

2024-05-13 22:17 UTC, takishida requested changes

2024-05-13 22:17 UTC, takishida commented on aci-preupgrade-validation-script.py
> +        subnet_scope_check,
Should be in the chunk for the configuration checks instead of the bug checks

2024-05-13 22:17 UTC, takishida commented on tests/subnet_scope_check/test_subnet_scope_check.py
> +
Not used.

2024-05-14 19:13 UTC, takishida approved these changes

2024-05-14 19:13 UTC, merged