Issue100
datacenter/ACI-Pre-Upgrade-Validation-Script pull request #130
Opened 2024-05-24 04:36 UTC by jeestr4d

2024-05-24 04:38 UTC, jeestr4d commented
Fix for Issue #100 
Local Pytest result

`tests/firmware32_64_bit_check/test_32_64_bit_firmware_check.py::test_logic[icurl_outputs0-5.2(7f)-6.0(2h)-FAIL - OUTAGE WARNING!!] PASSED                          [ 23%]
tests/firmware32_64_bit_check/test_32_64_bit_firmware_check.py::test_logic[icurl_outputs1-4.2(7f)-6.0(2h)-FAIL - OUTAGE WARNING!!] PASSED                          [ 23%]
tests/firmware32_64_bit_check/test_32_64_bit_firmware_check.py::test_logic[icurl_outputs2-5.2(7f)-6.0(2h)-PASS] PASSED                                             [ 24%]
tests/firmware32_64_bit_check/test_32_64_bit_firmware_check.py::test_logic[icurl_outputs3-5.1(1a)-5.2(7d)-N/A] PASSED                                              [ 24%]

`

2024-08-12 18:36 UTC, monrog2 commented
refactored logic and tests. added docs.

new pytest output:
```
[Check  1/1] 32 and 64-Bit Firmware Image for Switches...                                                        FAIL - UPGRADE FAILURE!!
  Target Switch Version  32-Bit Image Found  64-Bit Image Found
  ---------------------  ------------------  ------------------
  n9000-16.0(3e)         False               True

  Recommended Action: Upload the missing 32 or 64 bit Switch Image to the Firmware repository
  Reference Document: https://datacenter.github.io/ACI-Pre-Upgrade-Validation-Script/validations/#602-requires-32-and-64-bit-switch-images


[Check  1/1] 32 and 64-Bit Firmware Image for Switches...                                                        FAIL - UPGRADE FAILURE!!
  Target Switch Version  32-Bit Image Found  64-Bit Image Found
  ---------------------  ------------------  ------------------
  n9000-16.0(3e)         False               False

  Recommended Action: Upload the missing 32 or 64 bit Switch Image to the Firmware repository
  Reference Document: https://datacenter.github.io/ACI-Pre-Upgrade-Validation-Script/validations/#602-requires-32-and-64-bit-switch-images


[Check  1/1] 32 and 64-Bit Firmware Image for Switches...                                                                            PASS
[Check  1/1] 32 and 64-Bit Firmware Image for Switches... Target version below 6.0(2)                                                 N/A
```

Integration tests currently running

2024-08-12 19:42 UTC, monrog2 requested changes
merge master

2024-08-12 20:16 UTC, monrog2 submitted a review, later dismissed

2024-08-12 20:21 UTC, monrog2 approved these changes

2024-08-12 20:21 UTC, merged