added new postUpgradeCb check for CSCwe21982
datacenter/ACI-Pre-Upgrade-Validation-Script pull request #147
Opened 2024-08-11 10:57 UTC by welkin-he

folks,
can you please review this pull request?
Thanks,
welkin

2024-08-13 18:45 UTC, monrog2 requested changes

2024-08-13 18:45 UTC, monrog2 commented on aci-preupgrade-validation-script.py
> +            "SinceVersion": ["5.2(8d)","6.0(3d)"],
better to pick one data type for `SinceVersion` and handle that. If `list` gives you the most flexibility, then convert the rest

2024-08-13 18:45 UTC, monrog2 commented on aci-preupgrade-validation-script.py
> +        if isinstance(new_mo_dict[new_mo]['SinceVersion'],list):
If `list` gives you the most flexibility, convert the other entries to list and remove this check

2024-08-13 22:53 UTC, welkin-he commented on aci-preupgrade-validation-script.py
> +            "SinceVersion": ["5.2(8d)","6.0(3d)"],
sounds good, change is done.

2024-08-13 22:54 UTC, welkin-he commented on aci-preupgrade-validation-script.py
> +        if isinstance(new_mo_dict[new_mo]['SinceVersion'],list):
sounds good, changed.

2024-08-14 18:03 UTC, monrog2 approved these changes

2024-08-14 19:39 UTC, monrog2 commented
Updated pytest output:
```
[Check  1/1] Post Upgrade Callback Integrity... Re-run script after APICs are upgraded and back to Fully-Fit  POST UPGRADE CHECK REQUIRED
[Check  1/1] Post Upgrade Callback Integrity... Re-run script after APICs are upgraded and back to Fully-Fit  POST UPGRADE CHECK REQUIRED
[Check  1/1] Post Upgrade Callback Integrity...                                                                                      PASS
[Check  1/1] Post Upgrade Callback Integrity...                                                                                      PASS
[Check  1/1] Post Upgrade Callback Integrity...                                                                   FAIL - OUTAGE WARNING!!
  Missed Objects       Impact
  --------------       ------
  infraImplicitSetPol  Infra implicit settings will not be deployed

  Recommended Action: Contact Cisco TAC with Output
  Reference Document: https://datacenter.github.io/ACI-Pre-Upgrade-Validation-Script/validations/#post-upgrade-callback-integrity


[Check  1/1] Post Upgrade Callback Integrity...                                                                                      PASS
[Check  1/1] Post Upgrade Callback Integrity...                                                                   FAIL - OUTAGE WARNING!!
  Missed Objects       Impact
  --------------       ------
  fvSlaDef             IPSLA monitor policy will not be deployed
  infraImplicitSetPol  Infra implicit settings will not be deployed

  Recommended Action: Contact Cisco TAC with Output
  Reference Document: https://datacenter.github.io/ACI-Pre-Upgrade-Validation-Script/validations/#post-upgrade-callback-integrity


[Check  1/1] Post Upgrade Callback Integrity...                                                                                      PASS
[Check  1/1] Post Upgrade Callback Integrity...                                                                   FAIL - OUTAGE WARNING!!
  Missed Objects                   Impact
  --------------                   ------
  fvSlaDef                         IPSLA monitor policy will not be deployed
  infraAssocEncapInstDef           VLAN for missing Mo will not be deployed to leaf
  infraImplicitSetPol              Infra implicit settings will not be deployed
  infraRsConnectivityProfileOpt    VPC for missing Mo will not be deployed to leaf
  infraRsToInterfacePolProfileOpt  VLAN for missing Mo will not be deployed to leaf

  Recommended Action: Contact Cisco TAC with Output
  Reference Document: https://datacenter.github.io/ACI-Pre-Upgrade-Validation-Script/validations/#post-upgrade-callback-integrity


[Check  1/1] Post Upgrade Callback Integrity...                                                                                      PASS
[Check  1/1] Post Upgrade Callback Integrity...                                                                   FAIL - OUTAGE WARNING!!
  Missed Objects                   Impact
  --------------                   ------
  compatSwitchHw                   Unexpected 64/32 bit image can deploy to switches
  fvSlaDef                         IPSLA monitor policy will not be deployed
  infraAssocEncapInstDef           VLAN for missing Mo will not be deployed to leaf
  infraImplicitSetPol              Infra implicit settings will not be deployed
  infraRsConnectivityProfileOpt    VPC for missing Mo will not be deployed to leaf
  infraRsToInterfacePolProfileOpt  VLAN for missing Mo will not be deployed to leaf

  Recommended Action: Contact Cisco TAC with Output
  Reference Document: https://datacenter.github.io/ACI-Pre-Upgrade-Validation-Script/validations/#post-upgrade-callback-integrity
```

2024-08-14 20:48 UTC, monrog2 approved these changes

2024-08-14 20:48 UTC, merged