Commit for Issue-14
datacenter/ACI-Pre-Upgrade-Validation-Script pull request #17
Opened 2021-11-30 12:01 UTC by welkin0

Hello Team,

I simplify the logic for image integrity check, please review and let me know your comment. 

cheers,
welkin

2021-11-30 21:20 UTC, monrog2 requested changes
@takishida and @ristainoj were present during this review

2021-11-30 21:20 UTC, monrog2 commented on aci-preupgrade-validation-script.py
> +            if self.regex.group(i) > v.group(i):
Please disable your IDE formatter, we are collapsing small lines intentionally to reduce the time it takes to copy/paste the script for buffered terminals.

2021-12-01 00:27 UTC, welkin0 commented on aci-preupgrade-validation-script.py
> +            if self.regex.group(i) > v.group(i):
Sure, the required changes are applied to latest commit.

2021-12-07 22:35 UTC, merged

2021-12-07 22:48 UTC, monrog2 commented
#14