Commit for Issue-13
datacenter/ACI-Pre-Upgrade-Validation-Script pull request #18
Opened 2021-11-30 12:14 UTC by welkin0

Hello folks,

Please review this change for the APIC SSL validation before upgrading, this is to make sure SSL cert has appropriate format before upgrade, or it can cause cluster diverge and subsequent problem.

Thanks,
welkin

2021-11-30 20:48 UTC, monrog2 requested changes
reviewed with @takishida and @ristainoj

2021-11-30 20:48 UTC, monrog2 commented on aci-preupgrade-validation-script.py
> +    elif tv and (tv.same_as('3.2(7f)') or tv.same_as('4.1(1i)') or (
this is currently crashing if tversion is not supplied:
```
Traceback (most recent call last):
  File "preupgradeChecks.py", line 2245, in <module>
    r = check(idx + 1, len(checks), **inputs)
  File "preupgradeChecks.py", line 1665, in apic_ssl_certs_check
    elif tv and (tv.same_as('3.2(7f)') or tv.same_as('4.1(1i)') or (
UnboundLocalError: local variable 'tv' referenced before assignment
```
If tversion is not supplied, we should be falling back on MANUAL, simialr to these:
```
[Check  1/38] APIC Target version image and MD5 hash... Target version not supplied. Skipping.                       MANUAL CHECK REQUIRED
[Check  2/38] Target version compatibility... Target version not supplied. Skipping.                                 MANUAL CHECK REQUIRED
[Check  3/38] APIC SSL Certificate and SSH key Check... 
              Checking RCH-SV-APIC-StandaloneIII...... 1

              Error: local variable 'tv' referenced before assignment...                                                          ERROR !!
[Check  4/38] Gen 1 switch compatibility... Target version not supplied. Skipping.                                   MANUAL CHECK REQUIRED
[Check  5/38] Remote Leaf Compatibility... Target version not supplied. Skipping.                                    MANUAL CHECK REQUIRED
[Check  6/38] APIC CIMC Compatibility... Target version not supplied. Skipping.

2021-11-30 20:48 UTC, monrog2 commented on aci-preupgrade-validation-script.py
> +    if tversion:
you can add this above to basically skip running all the checks if tversion is not supplied:
```
    if not tversion:
        print_result(title, MANUAL, 'Target version not supplied. Skipping.')
        return MANUAL

2021-11-30 20:48 UTC, monrog2 commented on aci-preupgrade-validation-script.py
> +            data.append([attr['id'], attr['name'], '-', '-', '-',  e])
Check header formatting is becoming skewed as-is:
```
[Check  3/38] APIC SSL Certificate and SSH key Check... 
              Checking a-apic2......               Checking a-apic3......               Checking a-apic1......                                                                                                                   FAIL - UPGRADE FAILURE!!
  Node-Id  Name     OpenSSL-Check  Cert-format-check  SSH-check  Recommended Action
  -------  ----     -------------  -----------------  ---------  ------------------
  1        a-apic1  -              -                  -          failed to login to host
  2        a-apic2  -              -                  -          failed to login to host
  3        a-apic3  -              -                  -          failed to login to host
  ```
  
  Consider adding the following print result after this line:
  ```
  print_result(node_title, ERROR)

2021-11-30 20:48 UTC, monrog2 commented on aci-preupgrade-validation-script.py
> +    if not controller:
This might become redundant if we update the function to begin by checking `if not tversion: MANUAL`. Can potentially be removed to simplify the function.

Additionally, the `icurl` function already has an exception handler if the response contains an error.

2021-11-30 20:48 UTC, monrog2 commented on aci-preupgrade-validation-script.py
> +    elif len(checked_apic) >= 1 and not data:
`len(checked_apic) >= 1` should instead check against the number of APICs found via the controllers:
3 APIC cluster should check for 3, 5 APIC should check for 5, etc

`len(checked_apic) == len(controller)`

2021-11-30 20:48 UTC, monrog2 commented on aci-preupgrade-validation-script.py
> +    elif tv and (tv.same_as('3.2(7f)') or tv.same_as('4.1(1i)') or (
At second thought, this could probably just be removed. Regardless of version upgrade behavior differences, if `acidiag verifyapic` finds some cert issue we should flag it

2021-11-30 20:48 UTC, monrog2 commented on aci-preupgrade-validation-script.py
> +        msg = "At least one APIC has SSL Cert/SSH key issue"
If all APICs pass the check, then this is an overall check `PASS`. 
If at least 1 APIC hits a fail, then it should be a `FAIL_UF`. 

This `msg` could be used as the default `FAIL_UF` case but does not make sense for the `PASS` case

2021-12-06 23:22 UTC, welkin0 commented
The request changes have been made,Please review the latest commit.

2021-12-07 22:51 UTC, monrog2 commented
#13

2021-12-07 23:32 UTC, monrog2 requested changes

2021-12-07 23:32 UTC, monrog2 commented on aci-preupgrade-validation-script.py
> +    prints('')
this is causing formatting issues, should be removed:
```
[Check  2/38] Target version compatibility... Target version not supplied. Skipping.                                 MANUAL CHECK REQUIRED
[Check  3/38] APIC SSL Certificate and SSH key Check... 
Target version not supplied. Skipping.                       MANUAL CHECK REQUIRED
[Check  4/38] Gen 1 switch compatibility... Target version not supplied. Skipping.                                   MANUAL CHECK REQUIRED

2021-12-07 23:32 UTC, monrog2 commented on aci-preupgrade-validation-script.py
> +    else:
full success check is returning as FAIL_UF:
```
[Check  3/38] APIC SSL Certificate and SSH key Check... 
              Checking apic1......                                                                                                    DONE
              Checking apic2......                                                                                                    DONE
              Checking apic3......                                                                                                    DONE
                                                                                                                  FAIL - UPGRADE FAILURE!!

2021-12-08 00:38 UTC, monrog2 commented on aci-preupgrade-validation-script.py
> +    else:
fixed in https://github.com/datacenter/ACI-Pre-Upgrade-Validation-Script/pull/18/commits/d3b864a68b0c52d8e9e5ef8d97cbe668c813d6a3:
```
[Check  3/38] APIC SSL Certificate and SSH key Check... 
              Checking bdsol-aci19-apic1......                                                                                        DONE
              Checking bdsol-aci19-apic2......                                                                                        DONE
              Checking bdsol-aci19-apic3......                                                                                        DONE
                                                                                                                                      PASS
[Check  4/38] Gen 1 switch compatibility...

2021-12-08 00:39 UTC, monrog2 commented on aci-preupgrade-validation-script.py
> +    prints('')
removed the MANUAL case altogether, no longer need to check tversion

2021-12-08 00:44 UTC, monrog2 commented
@welkin0  can you do a negative test using above changes to validate that checks out. Positive hits are verified.

2024-04-25 20:36 UTC, closed without merging