59 fabric dpp check
datacenter/ACI-Pre-Upgrade-Validation-Script pull request #76
Opened 2023-09-21 07:28 UTC by kshcheku

Hello team,

Please review the changes for new validation #59 

Thank you

2024-04-11 05:58 UTC, takishida requested changes

2024-04-11 05:58 UTC, takishida commented on aci-preupgrade-validation-script.py
> +    title = 'Dynamic Packet Prioritization'
```suggestion
    title = 'CoS 3 with Dynamic Packet Prioritization'
```

2024-04-11 05:58 UTC, takishida commented on aci-preupgrade-validation-script.py
> +        if tversion.major1 == "5" and tversion.older_than("5.2(8e)") or tversion.major1 == "6" and tversion.older_than("6.0(3d)"):
This defect is applicable only when the target version is newer than a certain version X and older than the fixed versions you listed.

Need a confirmation but it appears that version X is 5.2(6e)? Can you please check the version X and add `tversion.newer_than(X)` to the first condition `tversion.major1 == "5" and tversion.older_than("5.2(8e)")`?

2024-04-11 05:58 UTC, takishida commented on aci-preupgrade-validation-script.py
> +    recommended_action = 'Review Software Advisory for details'
```suggestion
    recommended_action = 'Change the target version to the fixed version of CSCwf05073'
```

2024-04-11 05:58 UTC, takishida commented on docs/docs/validations.md
> +[Dynamic Packet Prioritization][d10]            | CSCwf05073   | :white_check_mark: | :no_entry_sign:           |:no_entry_sign:
```suggestion
[CoS 3 with Dynamic Packet Prioritization][d10]            | CSCwf05073   | :white_check_mark: | :no_entry_sign:           |:no_entry_sign:
```

2024-04-11 05:58 UTC, takishida commented on docs/docs/validations.md
> +[d10]: #dynamic-packet-prioritization
```suggestion
[d10]: #cos-3-with-dynamic-packet-prioritization
```

2024-04-11 05:58 UTC, takishida commented on docs/docs/validations.md
> +### Dynamic Packet Prioritization
```suggestion
### CoS 3 with Dynamic Packet Prioritization
```

2024-04-11 05:58 UTC, takishida commented on docs/docs/validations.md
> +In certain cases, such as when frames goes through FCoE supported devices, these get classified into the no drop FCoE class. In FCoE devices, this can cause drop off packets when the packet length is
```suggestion
In certain cases, such as when frames goes through FCoE supported devices, these get classified into the no drop FCoE class. In FCoE devices, this can cause drop of packets when the packet length is higher than the allowed 2184 bytes.
```

2024-04-11 05:58 UTC, takishida commented on tests/fabric_dpp_check/test_fabric_dpp_check.py
> +            "5.2(2h)",
Is this really an affected version?

2024-05-07 07:36 UTC, kshcheku commented
Hello guys, please verify the last commit. Thank you.

2024-05-07 20:42 UTC, takishida approved these changes

2024-05-07 20:43 UTC, merged