89 newvalidation mini aci upgrade to 602+
datacenter/ACI-Pre-Upgrade-Validation-Script pull request #93
Opened 2024-04-18 14:19 UTC by wilsonbc2

```
// tac_rtp_calo_b showing failure on upgrade
[Check 12/50] Mini ACI Upgrade to 6.0(2)+...                                                                      FAIL - UPGRADE FAILURE!!
  Pod ID  Node ID  APIC Type  Failure Reason
  ------  -------  ---------  --------------
  1       2        virtual    Virtual APIC must be removed prior to upgrade to 6.0(2)+
  1       3        virtual    Virtual APIC must be removed prior to upgrade to 6.0(2)+

  Recommended Action: All virtual APICs must be removed from the cluster prior to upgrading to 6.0(2)+.
  Reference Document: Upgrading or Downgrading Virtual APIC - http://cs.co/9009bBTQB

  
  
// Pytest is passing for all checks
$ pytest tests/test_logic.py --verbose
================================================================================================== test session starts ==================================================================================================
platform darwin -- Python 2.7.18, pytest-4.6.11, py-1.11.0, pluggy-0.13.1 -- /Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
cachedir: .pytest_cache
rootdir: /Users/benjwils/ApicAPI/ACI-Pre-Upgrade-Validation-Script/ACI-Pre-Upgrade-Validation-Script, inifile: pytest.ini
collected 25 items

tests/test_logic.py::test_aciversion PASSED                                                                                                                                                                       [  4%]
tests/test_logic.py::test_get_vpc_nodes PASSED                                                                                                                                                                    [  8%]
tests/test_logic.py::test_defect_eventmgr_db[3.2(5e)-4.2(4r)-PASS] PASSED                                                                                                                                         [ 12%]
tests/test_logic.py::test_defect_eventmgr_db[3.2(10g)-4.2(4r)-PASS] PASSED                                                                                                                                        [ 16%]
tests/test_logic.py::test_defect_eventmgr_db[4.1(2a)-4.2(7a)-PASS] PASSED                                                                                                                                         [ 20%]
tests/test_logic.py::test_defect_eventmgr_db[3.2(4a)-5.2(2a)-FAIL - UPGRADE FAILURE!!] PASSED                                                                                                                     [ 24%]
tests/test_logic.py::test_defect_eventmgr_db[4.0(1a)-5.2(3a)-FAIL - UPGRADE FAILURE!!] PASSED                                                                                                                     [ 28%]
tests/test_logic.py::test_encap_already_in_use_check[faultInst-encap-pos.json-fvIfConn.json-FAIL - OUTAGE WARNING!!] PASSED                                                                                       [ 32%]
tests/test_logic.py::test_encap_already_in_use_check[faultInst-encap-neg.json-fvIfConn.json-PASS] PASSED                                                                                                          [ 36%]
tests/test_logic.py::test_apic_ca_cert_validation[4.2(5e)-5.2(6e)-POS_certreq.txt-FAIL - OUTAGE WARNING!!]
----------------------------------------------------------------------------------------------------- live log call -----------------------------------------------------------------------------------------------------
11:20:44 DEBUG {"totalCount":"1","imdata":[{"error":{"attributes":{"code":"400","text":"CA not ready"}}}]}
PASSED                                                                                                                                                                                                            [ 40%]
tests/test_logic.py::test_apic_ca_cert_validation[4.2(4a)-5.2(2a)-NEG_certreq.txt-PASS]
----------------------------------------------------------------------------------------------------- live log call -----------------------------------------------------------------------------------------------------
11:20:44 DEBUG {"totalCount":"1","imdata":[{"aaaApplianceCertRes":{"attributes":{"blobres":"","certres":"-----BEGIN CERTIFICATE-----
MII...
-----END CERTIFICATE-----

","childAction":"","dn":"","hmac":"","keyres":"","lcOwn":"local","modTs":"never","rootres":"-----BEGIN CERTIFICATE-----
MII...
-----END CERTIFICATE-----
","status":"","type":"csvc"}}}]}
PASSED                                                                                                                                                                                                            [ 44%]
tests/test_logic.py::test_vpc_paired_switches_check PASSED                                                                                                                                                        [ 48%]
tests/test_logic.py::test_llfc_susceptibility_check PASSED                                                                                                                                                        [ 52%]
tests/test_logic.py::test_pos_telemetryStatsServerP_object_check PASSED                                                                                                                                           [ 56%]
tests/test_logic.py::test_neg_telemetryStatsServerP_object_check PASSED                                                                                                                                           [ 60%]
tests/test_logic.py::test_pos_isis_redis_metric_mpod_msite_check PASSED                                                                                                                                           [ 64%]
tests/test_logic.py::test_neg_isis_redis_metric_mpod_msite_check PASSED                                                                                                                                           [ 68%]
tests/test_logic.py::test_missing_isis_redis_metric_mpod_msite_check PASSED                                                                                                                                       [ 72%]
tests/test_logic.py::test_switch_bootflash_usage_check_new PASSED                                                                                                                                                 [ 76%]
tests/test_logic.py::test_contract_22_defect_check PASSED                                                                                                                                                         [ 80%]
tests/test_logic.py::test_pos_internal_vlanpool_check PASSED                                                                                                                                                      [ 84%]
tests/test_logic.py::test_neg_internal_vlanpool_check PASSED                                                                                                                                                      [ 88%]
tests/test_logic.py::test_bgp_golf_route_target_type_check PASSED                                                                                                                                                 [ 92%]
tests/test_logic.py::test_pos_mini_aci_6_0_2_check PASSED                                                                                                                                                         [ 96%]
tests/test_logic.py::test_neg_mini_aci_6_0_2_check PASSED                                                                                                                                                         [100%]

// Gitlab runner -- ignoring failures on these two fabrics as they are unrelated to the script
[2024-04-18 14:03:00 UTC ERROR root:221] (MainThread) ####################################
[2024-04-18 14:03:0 [...]

2024-04-20 00:50 UTC, takishida commented
@wilsonbc2 is working on pytest update and documentations

2024-04-20 00:51 UTC, takishida requested changes
@wilsonbc2 is working on pytest updates and documentation.

2024-04-24 14:04 UTC, wilsonbc2 commented
Pytest updates and documentation completed. Waiting for review @takishida .
```
< 16:41:14 benjwils > $ pytest test_mini_aci_6_0_2_check.py
====================================================================================================================================== test session starts =======================================================================================================================================
platform darwin -- Python 2.7.18, pytest-4.6.11, py-1.11.0, pluggy-0.13.1
rootdir: ./ACI-Pre-Upgrade-Validation-Script, inifile: pytest.ini
collected 7 items

test_mini_aci_6_0_2_check.py::test_logic[icurl_outputs0-3.2(1a)-5.2(6a)-PASS] PASSED                                                                                                                                                                                                       [ 14%]
test_mini_aci_6_0_2_check.py::test_logic[icurl_outputs1-6.0(2e)-6.0(5d)-PASS] PASSED                                                                                                                                                                                                       [ 28%]
test_mini_aci_6_0_2_check.py::test_logic[icurl_outputs2-5.2(3a)-6.0(3d)-PASS] PASSED                                                                                                                                                                                                       [ 42%]
test_mini_aci_6_0_2_check.py::test_logic[icurl_outputs3-4.1(1a)-5.2(7f)-PASS] PASSED                                                                                                                                                                                                       [ 57%]
test_mini_aci_6_0_2_check.py::test_logic[icurl_outputs4-4.2(2a)-6.0(2c)-FAIL - UPGRADE FAILURE!!] PASSED                                                                                                                                                                                   [ 71%]
test_mini_aci_6_0_2_check.py::test_logic[icurl_outputs5-6.0(1a)-6.0(2c)-FAIL - UPGRADE FAILURE!!] PASSED                                                                                                                                                                                   [ 85%]
test_mini_aci_6_0_2_check.py::test_logic[icurl_outputs6-6.0(2c)-6.0(5c)-PASS] PASSED                                                                                                                                                                                                       [100%]

==================================================================================================================================== 7 passed in 0.05 seconds ====================================================================================================================================
```

2024-04-24 16:31 UTC, takishida approved these changes

2024-04-24 16:32 UTC, merged