address CSCwj69435 for the afected versions
datacenter/ACI-Pre-Upgrade-Validation-Script pull request #96
Opened 2024-04-19 11:33 UTC by ehaminian

Following a recent outage with one of our clients, we've noticed an issue with the APIC failing to reject configurations where "Access(untagged)" mode is applied to a single interface across multiple EPGs. This configuration oversight, likely due to user error, poses a significant risk. Any switch reprogramming trigger could inadvertently deploy new VLANs/EPGs on interfaces, a scenario that should be prevented by the APIC during configuration.

To address this issue, we've filled a defect under CSCwj69435. We've also introduced a new validation mechanism, titled "Overlapping Access (Untagged) mode on interfaces," which will detect and warn customers about this issue before any upgrades are performed.

This validation process involves checking individual interfaces/port-channels, VPC interfaces, and FEX interfaces using the three regex patterns defined in the code.

2024-04-20 03:24 UTC, takishida requested changes
Thank you for the PR.

This is a good catch, but this check falls in to the same category as the following checks in the sense of fault F0467:

* `port_configured_for_apic_check`
* `port_configured_as_l2_check`
* `port_configured_as_l3_check`
* `prefix_already_in_use_check`
* `encap_already_in_use_check`

As you can see from the fault below, it's the same fault as the checks shown above, but with a different `configQual` in the `changeSet`. 

```
admin@apic1:~> moquery -c faultInst  -x 'query-target-filter=wcard(faultInst.changeSet,"native-or-untagged-encap-failure")'
Total Objects shown: 1

# fault.Inst
code             : F0467
ack              : no
alert            : no
annotation       :
cause            : configuration-failed
changeSet        : configQual (New: native-or-untagged-encap-failure), debugMessage (New: )
childAction      :
created          : 2024-04-19T17:57:59.887-07:00
delegated        : yes
descr            : Configuration failed for uni/tn-TK/ap-AP1/epg-EPG1-2 node 101 eth1/4 due to Only One Native or Untagged Encap Allowed on Interface, debug message:
dn               : topology/pod-1/node-101/local/svc-policyelem-id-0/uni/epp/fv-[uni/tn-TK/ap-AP1/epg-EPG1-2]/node-101/stpathatt-[eth1/4]/nwissues/fault-F0467
domain           : tenant
extMngdBy        : undefined
highestSeverity  : minor
lastTransition   : 2024-04-19T18:00:23.777-07:00
lc               : raised
modTs            : never
occur            : 1
origSeverity     : minor
prevSeverity     : minor
rn               : fault-F0467
rule             : fv-nw-issues-config-failed
severity         : minor
status           :
subject          : management
title            :
type             : config
uid              :
userdom          : all
```

For consistency and extensibility, we should follow the same approach as the other F0467 checks. Meaning, we should check the fault instead of checking all the configuration. That way, in the future, we could combine the queries for all checks with F0467 into one if we want. The reason why the queries are separated for now is to prevent the script from being silent for a long time due to a big query. Even if the total amount of time may be longer, we preferred finishing each check quicker so users can see the progress more often. But we may change this in the future.

With that said, would you mind updating the logic to follow the other checks shown above?

For consistency sake, I would also change the title to `Access (Untagged) Port Config (F0467 native-or-untagged-encap-failure)`.

Also please add pytest and docs. You can see the examples for both from PR #92.

2024-04-20 13:51 UTC, ehaminian commented
Hello takishida,

Thanks for the review and the comments.
The requested changes were applied.
Please let me know if there is anything missing.

2024-04-22 17:25 UTC, takishida requested changes

2024-04-22 17:25 UTC, takishida commented on aci-preupgrade-validation-script.py
> +    doc_url = 'https://bst.cloudapps.cisco.com/bugsearch/bug/CSCwj69435'
```suggestion
    doc_url = 'https://datacenter.github.io/ACI-Pre-Upgrade-Validation-Script/validations#native-or-untagged-encap-failure'
```

2024-04-22 17:25 UTC, takishida commented on aci-preupgrade-validation-script.py
> +            if m:
Please add `else` to handle a case when the regex is not matching.
Since a fault may be raised against a different type of DN or object, it's common to overlook some corner cases which are not covered by the regex. To avoid those cases being marked as `PASS` incorrectly, we have `unformatted_headers` and `unformatted_data` just to dump the fault description. Please see other F0467 checks for examples.

2024-04-22 17:25 UTC, takishida commented on docs/docs/validations.md
> +[Access (Untagged) Port Config][f17] | F0467: native-or-untagged-encap-failure | :white_check_mark: | :no_entry_sign: | :white_check_mark:
```suggestion
[Access (Untagged) Port Config][f17] | F0467: native-or-untagged-encap-failure | :white_check_mark: | :no_entry_sign: | :no_entry_sign:
```

Also would you mind moving this up to right beneath `[L2 Port Config][f8]` as `[Access (Untagged) Port Config][f9]`, then increment the reference number of others (`f9`-`f16`) by 1 to adjust? That way, it'd be easier to comb through the list as all F0467 checks are next to each other.

2024-04-22 17:25 UTC, takishida commented on docs/docs/validations.md
> +[f17]: #native-or-untagged-encap-failure
Same ask as the above. Move this up as `f9`, please.

2024-04-22 17:25 UTC, takishida commented on docs/docs/validations.md
> +```
This codeblock needs indentations with 4 spaces to be inside the example note.

2024-04-22 17:30 UTC, takishida requested changes

2024-04-22 17:30 UTC, takishida commented on docs/docs/validations.md
> +### Native or untagged encap failure
```suggestion
### Access (Untagged) Port Config
```

Let's match the section title with the name in the summary table.

2024-04-22 18:52 UTC, ehaminian commented on docs/docs/validations.md
> +```
Done!

2024-04-22 18:52 UTC, ehaminian reviewed
codeblock needs indentations with 4 spaces to be inside the example note.

2024-04-23 00:54 UTC, ehaminian commented on aci-preupgrade-validation-script.py
> +            if m:
Done!

2024-04-23 01:20 UTC, ehaminian commented
> Same ask as the above. Move this up as `f9`, please.

Also let's use the same title as the table, meaning `#access-untagged-port-config`

2024-04-23 01:22 UTC, ehaminian commented
> > Same ask as the above. Move this up as `f9`, please.

> Also let's use the same title as the table, meaning `#access-untagged-port-config` 

> Done!

2024-04-23 01:24 UTC, ehaminian commented on docs/docs/validations.md
> +[Access (Untagged) Port Config][f17] | F0467: native-or-untagged-encap-failure | :white_check_mark: | :no_entry_sign: | :white_check_mark:
Done!

2024-04-23 01:24 UTC, ehaminian commented on docs/docs/validations.md
> +[f17]: #native-or-untagged-encap-failure
Done!

2024-04-23 18:31 UTC, takishida requested changes

2024-04-23 18:31 UTC, takishida commented on docs/docs/validations.md
> +[Access (Untagged) Port Config][9] | F0467: native-or-untagged-encap-failure | :white_check_mark: | :no_entry_sign: | :no_entry_sign:
```suggestion
[Access (Untagged) Port Config][f9]            | F0467: native-or-untagged-encap-failure | :white_check_mark: | :no_entry_sign: | :no_entry_sign:
```

2024-04-23 18:31 UTC, takishida commented on docs/docs/validations.md
> +[f9]: #native-or-untagged-encap-failure
```suggestion
[f9]: #access-untagged-port-config
```

2024-04-23 18:31 UTC, takishida commented on docs/docs/validations.md
> +The script verifies these faults to ensure that a port is not configured as part of two access VLANs. It is expected that the customer resolves the conflict causing this fault before any upgrades to
```suggestion
The script verifies these faults to ensure that a port is not configured as part of two access VLANs. You need to resolve the conflict causing this fault before any upgrades to prevent potential outages. Failure to do so may result in the deployment of a new VLAN/EPG on the port after the upgrade, leading to downtime in the environment.
```

2024-04-23 18:51 UTC, ehaminian commented on docs/docs/validations.md
> +[f9]: #native-or-untagged-encap-failure
Done!

2024-04-23 18:52 UTC, ehaminian commented on docs/docs/validations.md
> +[Access (Untagged) Port Config][9] | F0467: native-or-untagged-encap-failure | :white_check_mark: | :no_entry_sign: | :no_entry_sign:
Done!

2024-04-23 19:02 UTC, ehaminian commented on docs/docs/validations.md
> +The script verifies these faults to ensure that a port is not configured as part of two access VLANs. It is expected that the customer resolves the conflict causing this fault before any upgrades to
Done!

2024-04-23 19:04 UTC, ehaminian commented on docs/docs/validations.md
> +The script verifies these faults to ensure that a port is not configured as part of two access VLANs. It is expected that the customer resolves the conflict causing this fault before any upgrades to
Done!

2024-04-23 19:15 UTC, merged